# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from algorithms import *
from draw import Draw
 

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimplify = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimplify.setObjectName("menuSimplify")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(parent=MainForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionMin_Bounding_Rectangle = QtGui.QAction(parent=MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/maer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionMin_Bounding_Rectangle.setIcon(icon1)
        self.actionMin_Bounding_Rectangle.setObjectName("actionMin_Bounding_Rectangle")
        self.actionPCAS = QtGui.QAction(parent=MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pca.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPCAS.setIcon(icon2)
        self.actionPCAS.setObjectName("actionPCAS")
        self.actionClear_results = QtGui.QAction(parent=MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/clear_ch.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon3)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/clear_er.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon4)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionLongest_Edge = QtGui.QAction(parent=MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/longestedge.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLongest_Edge.setIcon(icon5)
        self.actionLongest_Edge.setObjectName("actionLongest_Edge")
        self.actionWall_Average = QtGui.QAction(parent=MainForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/wa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWall_Average.setIcon(icon6)
        self.actionWall_Average.setObjectName("actionWall_Average")
        self.actionWeighted_bisector = QtGui.QAction(parent=MainForm)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/weightedbisector.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWeighted_bisector.setIcon(icon7)
        self.actionWeighted_bisector.setObjectName("actionWeighted_bisector")
        self.actionOpen = QtGui.QAction(parent=MainForm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon8)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSimplify.addAction(self.actionMin_Bounding_Rectangle)
        self.menuSimplify.addAction(self.actionPCAS)
        self.menuSimplify.addAction(self.actionLongest_Edge)
        self.menuSimplify.addAction(self.actionWall_Average)
        self.menuSimplify.addAction(self.actionWeighted_bisector)
        self.menuView.addAction(self.actionClear_results)
        self.menuView.addAction(self.actionClear_all)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimplify.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMin_Bounding_Rectangle)
        self.toolBar.addAction(self.actionPCAS)
        self.toolBar.addAction(self.actionLongest_Edge)
        self.toolBar.addAction(self.actionWall_Average)
        self.toolBar.addAction(self.actionWeighted_bisector)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        
        self.actionOpen.triggered.connect(self.openFileClick)
        self.actionExit.triggered.connect(self.exitClick)
        self.actionClear_all.triggered.connect(self.clearAllClick)
        self.actionMin_Bounding_Rectangle.triggered.connect(self.simplifyBuildingMBRClick)
        self.actionPCAS.triggered.connect(self.simplifyBuildingPCAClick)
        self.actionLongest_Edge.triggered.connect(self.simplifyBuildingLongestEdgeClick)
        self.actionWall_Average.triggered.connect(self.simplifyBuildingWallAverageClick)
        self.actionWeighted_bisector.triggered.connect(self.simplifyBuildingWWeightedBisectorClick)
        self.actionClear_results.triggered.connect(self.clearResultsClick)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        
        
    def simplifyBuildingPCAClick(self):
        #Get input data (list of polygons)
        buildings = self.Canvas.getBuilding()
        
        #Initialization of results
        buildings_simp = []
        a = Algorithms()
        
        #Run simplification for all buildings
        for i in buildings:
            if len(i) > 2:
                res = a.simplifyBuildingPCA(i)
                buildings_simp.append(res)
        
        #Set results to canvas and repaint
        self.Canvas.setSimplifBuilding(buildings_simp)
        self.Canvas.repaint()
        self.evaluateAccuracy()
        
    def simplifyBuildingMBRClick(self):
        #Get input data (list of polygons)
        buildings = self.Canvas.getBuilding()
        
        #Initialization of results
        buildings_simp = []
        a = Algorithms()
    
        #Run simplification for all buildings
        for i in buildings:
            if len(i) > 2:
                res = a.simplifyBuildingMBR(i)
                buildings_simp.append(res)
        
        #Set results to canvas and repaint
        self.Canvas.setSimplifBuilding(buildings_simp)
        self.Canvas.repaint()
        self.evaluateAccuracy()
            
    def simplifyBuildingLongestEdgeClick(self):
        #Get input data (list of polygons)
        buildings = self.Canvas.getBuilding()
        
        #Initialization of results
        buildings_simp = []
        a = Algorithms()
        
        #Run simplification for all buildings
        for i in buildings:
            if len(i) > 2:
                res, sigma = a.simplifyBuildingLongestEdge(i)
                buildings_simp.append(res)
        
        #Set results to canvas and repaint
        self.Canvas.setSimplifBuilding(buildings_simp)
        self.Canvas.repaint()
        self.evaluateAccuracy()
        
    def simplifyBuildingWallAverageClick(self):
        #Get input data (list of polygons)
        buildings = self.Canvas.getBuilding()
        
        #Initialization of results
        buildings_simp = []
        a = Algorithms()
        
        #Run simplification for all buildings
        for i in buildings:
            if len(i) > 2:
                res, sigma = a.simplifyBuildingWallAverage(i)
                buildings_simp.append(res)
        
        #Set results to canvas and repaint
        self.Canvas.setSimplifBuilding(buildings_simp)
        self.Canvas.repaint()
        self.evaluateAccuracy()
            
            
    def simplifyBuildingWWeightedBisectorClick(self):
        #Get input data (list of polygons)
        buildings = self.Canvas.getBuilding()
        
        #Initialization of results
        buildings_simp = []
        a = Algorithms()
        
        #Run simplification for all buildings
        for i in buildings:
            if len(i) > 2:
                res, sigma = a.simplifyBuildingWeightedBisector(i)
                buildings_simp.append(res)
        
        #Set results to canvas and repaint
        self.Canvas.setSimplifBuilding(buildings_simp)
        self.Canvas.repaint()   
        self.evaluateAccuracy()
        
    def openFileClick(self):
        #Open SHP file through Canvas method
        self.Canvas.openFile()
        
    def exitClick(self):
        #Close application
        QtWidgets.QApplication.instance().quit()

    def clearResultsClick(self):
        #Clear results
        self.Canvas.clearResult()
        
    def clearAllClick(self):
        #Clear everything
        self.Canvas.clearAll()
        
    # AI plus own lines 240 - 270
    def evaluateAccuracy(self):
        budovy = self.Canvas.getBuilding()
        if len(budovy) == 0: 
            return

        a = Algorithms()
        vysledky = [0, 0, 0, 0, 0]
        pocet = 0
        
        for b in budovy:
            plocha = a.getArea(b)
            if len(b) > 2 and plocha > 0:
                pocet += 1
                
                # Compute accuracy for each simplification method
                vysledky[0] += a.getArea(b.intersected(a.simplifyBuildingPCA(b))) / plocha
                vysledky[1] += a.getArea(b.intersected(a.simplifyBuildingMBR(b))) / plocha
                vysledky[2] += a.getArea(b.intersected(a.simplifyBuildingLongestEdge(b)[0])) / plocha
                vysledky[3] += a.getArea(b.intersected(a.simplifyBuildingWallAverage(b)[0])) / plocha
                vysledky[4] += a.getArea(b.intersected(a.simplifyBuildingWeightedBisector(b)[0])) / plocha
                    
        if pocet > 0:
            t = "Vysledky metod:\n"
            t += "PCA: " + str(round((vysledky[0]/pocet)*100)) + " %\n"
            t += "MBR: " + str(round((vysledky[1]/pocet)*100)) + " %\n"
            t += "Longest Edge: " + str(round((vysledky[2]/pocet)*100)) + " %\n"
            t += "Wall Average: " + str(round((vysledky[3]/pocet)*100)) + " %\n"
            t += "Weighted Bisector: " + str(round((vysledky[4]/pocet)*100)) + " %\n"
            
            # Display results in a message box
            QtWidgets.QMessageBox.information(None, "Info", t)
    
    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Simplify buildings"))
        self.menuFile.setTitle(_translate("MainForm", "File"))
        self.menuSimplify.setTitle(_translate("MainForm", "Simplify"))
        self.menuView.setTitle(_translate("MainForm", "View"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionExit.setText(_translate("MainForm", "Exit"))
        self.actionExit.setToolTip(_translate("MainForm", "Close application"))
        self.actionMin_Bounding_Rectangle.setText(_translate("MainForm", "Min. Bounding Rectangle"))
        self.actionMin_Bounding_Rectangle.setToolTip(_translate("MainForm", "Simplify building using minimum bounding rectangle"))
        self.actionPCAS.setText(_translate("MainForm", "PCA"))
        self.actionPCAS.setToolTip(_translate("MainForm", "Simplify building using PCA"))
        self.actionClear_results.setText(_translate("MainForm", "Clear results"))
        self.actionClear_all.setText(_translate("MainForm", "Clear all"))
        self.actionClear_all.setToolTip(_translate("MainForm", "Clear all data"))
        self.actionLongest_Edge.setText(_translate("MainForm", "Longest Edge"))
        self.actionLongest_Edge.setToolTip(_translate("MainForm", "Simplify building using longest edge"))
        self.actionWall_Average.setText(_translate("MainForm", "Wall Average"))
        self.actionWall_Average.setToolTip(_translate("MainForm", "Simplify building using wall average"))
        self.actionWeighted_bisector.setText(_translate("MainForm", "Weighted Bisector"))
        self.actionWeighted_bisector.setToolTip(_translate("MainForm", "Simplify building using weighted bisector"))
        self.actionOpen.setText(_translate("MainForm", "Open"))
        self.actionOpen.setToolTip(_translate("MainForm", "Open file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec())